# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: users.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'users.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0busers.proto\x12\rservice.users\"A\n\x04User\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x0b\n\x03\x61ge\x18\x03 \x01(\x05\x12\x0f\n\x07hobbies\x18\x04 \x03(\t\"N\n\x11\x43reateUserRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x0b\n\x03\x61ge\x18\x03 \x01(\x05\x12\x0f\n\x07hobbies\x18\x04 \x03(\t\"7\n\x12\x43reateUserResponse\x12!\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x13.service.users.User\"\x1c\n\x0eGetUserRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"4\n\x0fGetUserResponse\x12!\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x13.service.users.User\"\x11\n\x0fGetUsersRequest\"5\n\x10GetUsersResponse\x12!\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x13.service.users.User2\xfd\x01\n\x0bUserService\x12S\n\nCreateUser\x12 .service.users.CreateUserRequest\x1a!.service.users.CreateUserResponse\"\x00\x12M\n\x08GetUsers\x12\x1e.service.users.GetUsersRequest\x1a\x1f.service.users.GetUsersResponse\"\x00\x12J\n\x07GetUser\x12\x1d.service.users.GetUserRequest\x1a\x1e.service.users.GetUserResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'users_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USER']._serialized_start=30
  _globals['_USER']._serialized_end=95
  _globals['_CREATEUSERREQUEST']._serialized_start=97
  _globals['_CREATEUSERREQUEST']._serialized_end=175
  _globals['_CREATEUSERRESPONSE']._serialized_start=177
  _globals['_CREATEUSERRESPONSE']._serialized_end=232
  _globals['_GETUSERREQUEST']._serialized_start=234
  _globals['_GETUSERREQUEST']._serialized_end=262
  _globals['_GETUSERRESPONSE']._serialized_start=264
  _globals['_GETUSERRESPONSE']._serialized_end=316
  _globals['_GETUSERSREQUEST']._serialized_start=318
  _globals['_GETUSERSREQUEST']._serialized_end=335
  _globals['_GETUSERSRESPONSE']._serialized_start=337
  _globals['_GETUSERSRESPONSE']._serialized_end=390
  _globals['_USERSERVICE']._serialized_start=393
  _globals['_USERSERVICE']._serialized_end=646
# @@protoc_insertion_point(module_scope)
